"""Generates every logo/icon file of Rokoso from one geometric definition.

Usage (from the project root, Python 3 and Google Chrome required):
    python docs/logo/generate.py

The mark: a ring with 16 rays in 22.5° steps (axes longest, diagonals shorter, in-between rays shortest).
Small sizes (favicon) use the reduced 8-ray form, because 16 rays blur below ~32 px.
PNGs are rendered with headless Chrome (no image library needed), the ICO wraps PNGs.
"""

import math
import os
import struct
import subprocess
import tempfile

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
CHROME = os.environ.get('CHROME', r'C:\Program Files\Google\Chrome\Application\chrome.exe')

BRAND = '#417230'
WHITE = '#fff'

# coordinates in a 100×100 box centred on 0/0
FINE = dict(stroke=1.6, ring_r=8.5, start=12, lengths=(46, 43, 39.5), rays=16)
BOLD = dict(stroke=4.2, ring_r=9, start=16, lengths=(45, 42, 37.5), rays=16)
SMALL = dict(stroke=7, ring_r=10, start=20, lengths=(44, 38), rays=8)


def ray_path(stroke, ring_r, start, lengths, rays):
    parts = []
    for k in range(rays):
        a = math.radians(k * 360 / rays - 90)
        if rays == 8:
            length = lengths[0 if k % 2 == 0 else 1]
        else:
            length = lengths[0 if k % 4 == 0 else (1 if k % 2 == 0 else 2)]
        x1, y1 = start * math.cos(a), start * math.sin(a)
        x2, y2 = length * math.cos(a), length * math.sin(a)
        parts.append(f'M{x1:.2f} {y1:.2f}L{x2:.2f} {y2:.2f}')
    return ''.join(parts).replace('-0.00', '0.00').replace('.00', '')


def mark(spec, stroke_attr):
    return (f'<g fill="none" {stroke_attr} stroke-width="{spec["stroke"]}" stroke-linecap="round">'
            f'<circle r="{spec["ring_r"]}"/><path d="{ray_path(**spec)}"/></g>')


def icon(spec, pad, radius, color=WHITE, bg=BRAND):
    """Square app icon: mark on a (rounded) brand tile."""
    vb = 100 + 2 * pad
    o = -vb / 2
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{o:g} {o:g} {vb:g} {vb:g}">'
            f'<rect x="{o:g}" y="{o:g}" width="{vb:g}" height="{vb:g}" rx="{radius:g}" fill="{bg}"/>'
            + mark(spec, f'stroke="{color}"') + '</svg>\n')


def write(path, content, mode='w'):
    full = os.path.join(ROOT, path)
    os.makedirs(os.path.dirname(full), exist_ok=True)
    text = {} if 'b' in mode else {'encoding': 'utf-8', 'newline': '\n'}
    with open(full, mode, **text) as f:
        f.write(content)
    print('wrote', path)


def png(svg, size):
    """Renders an SVG to a transparent PNG of size×size with headless Chrome."""
    with tempfile.TemporaryDirectory() as tmp:
        with open(os.path.join(tmp, 'i.svg'), 'w') as f:
            f.write(svg)
        with open(os.path.join(tmp, 'i.html'), 'w') as f:
            f.write(f'<style>html,body{{margin:0;background:transparent}}</style>'
                    f'<img src="i.svg" style="display:block;width:{size}px;height:{size}px">')
        out = os.path.join(tmp, 'i.png')
        subprocess.run([CHROME, '--headless', '--disable-gpu', '--hide-scrollbars',
                        '--default-background-color=00000000', f'--screenshot={out}',
                        f'--window-size={size},{size}', 'file:///' + os.path.join(tmp, 'i.html').replace('\\', '/')],
                       check=True, capture_output=True)
        with open(out, 'rb') as f:
            return f.read()


def ico(images):
    """ICO file with embedded PNGs (supported by all current browsers)."""
    head = struct.pack('<HHH', 0, 1, len(images))
    offset = 6 + 16 * len(images)
    entries, data = b'', b''
    for size, blob in images:
        entries += struct.pack('<BBBBHHII', size % 256, size % 256, 0, 0, 1, 32, len(blob), offset + len(data))
        data += blob
    return head + entries + data


# Twig partial: inline marks (colour via Tailwind classes, decorative – the name stays as text)
write('templates/_partials/logo.html.twig', f'''{{# Generated by docs/logo/generate.py – do not edit by hand.
   variant: "tile" (white mark on brand tile, small sizes) or "line" (fine mark in the current text colour). #}}
{{% set variant = variant|default('tile') %}}
{{% if variant == 'line' %}}
<svg viewBox="-50 -50 100 100" class="{{{{ class|default('size-16 text-brand-600') }}}}" aria-hidden="true" focusable="false">{mark(FINE, 'stroke="currentColor"')}</svg>
{{% else %}}
<svg viewBox="-62 -62 124 124" class="{{{{ class|default('size-8') }}}}" aria-hidden="true" focusable="false"><rect x="-62" y="-62" width="124" height="124" rx="26" class="fill-brand-600"/>{mark(BOLD, 'class="stroke-white"')}</svg>
{{% endif %}}
''')

write('assets/images/logo.svg', '<svg xmlns="http://www.w3.org/2000/svg" viewBox="-50 -50 100 100">'
      + mark(FINE, f'stroke="{BRAND}"') + '</svg>\n')

app_icon = icon(BOLD, pad=12, radius=26)            # rounded tile, transparent corners
full_icon = icon(BOLD, pad=14, radius=0)            # iOS rounds itself
maskable = icon(BOLD, pad=22, radius=0)             # mark inside the 80 % safe zone
small = icon(SMALL, pad=10, radius=26)

write('public/favicon.svg', small)
write('public/icons/icon.svg', app_icon)
write('assets/images/logo-icon.svg', app_icon)
write('public/favicon.ico', ico([(16, png(small, 16)), (32, png(small, 32)), (48, png(app_icon, 48))]), 'wb')
for name, svg, size in [('icon-192.png', app_icon, 192), ('icon-512.png', app_icon, 512),
                        ('icon-maskable-512.png', maskable, 512), ('apple-touch-icon.png', full_icon, 180),
                        ('email-logo.png', app_icon, 64)]:
    write('public/icons/' + name, png(svg, size), 'wb')
