date.timezone = Europe/Berlin
memory_limit = 256M
upload_max_filesize = 50M
post_max_size = 200M
max_file_uploads = 20
expose_php = Off
opcache.enable = 1
opcache.validate_timestamps = 0
opcache.memory_consumption = 128
realpath_cache_size = 4096K
realpath_cache_ttl = 600
