<?php

declare(strict_types=1);

namespace App\Asset;

use Symfony\Component\DependencyInjection\Attribute\Autowire;
use Symfony\Component\Process\Process;
use Symfony\Contracts\HttpClient\HttpClientInterface;

/**
 * Bundles all JavaScript into one file (var/js/build/app.js) with the esbuild standalone binary (MIT) – no Node needed.
 * AssetMapper serves the result as "build/app.js" with a content hash in the URL.
 *
 * Stimulus controllers are registered from a generated module (var/js/controllers.js, imported as "@app/controllers"):
 * every assets/controllers/**\/*_controller.js, name like StimulusBundle ("foo_bar" → "foo-bar", sub/x → "sub--x").
 * Third-party packages (@hotwired/…) come from importmap.php / assets/vendor (`importmap:install`).
 */
final readonly class JsBundler
{
    public const string VERSION = '0.28.2';

    public function __construct(
        #[Autowire('%kernel.project_dir%')]
        private string $projectDir,
        private HttpClientInterface $httpClient,
    ) {
    }

    /**
     * @param callable(string): void $output
     */
    public function build(bool $minify, bool $watch, callable $output): int
    {
        $this->writeControllers();
        $args = [$this->binary($output), 'assets/app.js', '--bundle', '--format=esm', '--target=es2022', '--charset=utf8',
            '--outfile=var/js/build/app.js', '--log-level=warning', '--alias:@app/controllers=./var/js/controllers.js'];
        foreach ($this->vendorPackages() as $name => $path) {
            $args[] = '--alias:'.$name.'=./'.$path;
        }
        $args = [...$args, ...($minify ? ['--minify'] : ['--sourcemap=inline']), ...($watch ? ['--watch=forever'] : [])];

        $process = new Process($args, $this->projectDir, timeout: null);
        $process->run(static function (string $type, string $buffer) use ($output): void {
            $output($buffer);
        });

        return $process->getExitCode() ?? 1;
    }

    /**
     * Versioned packages from importmap.php, downloaded to assets/vendor/<name>/<basename>.index.js.
     *
     * @return array<string, string>
     */
    private function vendorPackages(): array
    {
        /** @var array<string, array{version?: string}> $map */
        $map = require $this->projectDir.'/importmap.php';
        $packages = [];
        foreach ($map as $name => $entry) {
            if (!isset($entry['version'])) {
                continue;
            }
            $path = 'assets/vendor/'.$name.'/'.basename($name).'.index.js';
            if (!is_file($this->projectDir.'/'.$path)) {
                throw new \RuntimeException(\sprintf('"%s" is missing – run "php bin/console importmap:install".', $path));
            }
            $packages[$name] = $path;
        }

        return $packages;
    }

    private function writeControllers(): void
    {
        $base = $this->projectDir.'/assets/controllers';
        $files = [];
        $iterator = new \RecursiveIteratorIterator(new \RecursiveDirectoryIterator($base, \FilesystemIterator::SKIP_DOTS));
        foreach ($iterator as $file) {
            /** @var \SplFileInfo $file */
            $relative = str_replace('\\', '/', substr($file->getPathname(), \strlen($base) + 1));
            if (str_ends_with($relative, '_controller.js')) {
                $files[] = $relative;
            }
        }
        sort($files);

        $imports = [
            '// Generated by app:js:build – do not edit.',
            "import '@hotwired/turbo';",
            "import TurboCore from '../../vendor/symfony/ux-turbo/assets/dist/turbo_controller.js';",
        ];
        $entries = ["    'symfony--ux-turbo--turbo-core': TurboCore,"];
        foreach ($files as $i => $relative) {
            $source = (string) file_get_contents($base.'/'.$relative);
            // Symfony's CSRF helper only registers event listeners and exports a string instead of a controller
            if (!preg_match('/export\s+default\s+class\b/', $source)) {
                $imports[] = \sprintf("import '../../assets/controllers/%s';", $relative);
                continue;
            }
            $name = str_replace(['_', '/'], ['-', '--'], substr($relative, 0, -\strlen('_controller.js')));
            $imports[] = \sprintf("import C%d from '../../assets/controllers/%s';", $i, $relative);
            $entries[] = \sprintf("    '%s': C%d,", $name, $i);
        }

        $dir = $this->projectDir.'/var/js';
        if (!is_dir($dir)) {
            mkdir($dir, 0o777, true);
        }
        $content = implode("\n", $imports)."\n\nexport default {\n".implode("\n", $entries)."\n};\n";
        if (!is_file($dir.'/controllers.js') || file_get_contents($dir.'/controllers.js') !== $content) {
            file_put_contents($dir.'/controllers.js', $content);
        }
    }

    /**
     * Path of the esbuild binary; downloaded once from the npm registry (checksum verified) into var/esbuild.
     *
     * @param callable(string): void $output
     */
    private function binary(callable $output): string
    {
        $windows = \PHP_OS_FAMILY === 'Windows';
        $os = match (\PHP_OS_FAMILY) {
            'Windows' => 'win32',
            'Darwin' => 'darwin',
            default => 'linux',
        };
        $arch = \in_array(strtolower(php_uname('m')), ['arm64', 'aarch64'], true) ? 'arm64' : 'x64';
        $package = $os.'-'.$arch;
        $dir = $this->projectDir.'/var/esbuild/'.self::VERSION.'-'.$package;
        $binary = $dir.'/'.($windows ? 'esbuild.exe' : 'esbuild');
        if (is_file($binary)) {
            return $binary;
        }

        $output(\sprintf("Downloading esbuild %s (%s) …\n", self::VERSION, $package));
        /** @var array{dist: array{tarball: string, integrity: string}} $meta */
        $meta = $this->httpClient->request('GET', \sprintf('https://registry.npmjs.org/@esbuild/%s/%s', $package, self::VERSION))->toArray();
        $tarball = $this->httpClient->request('GET', $meta['dist']['tarball'])->getContent();
        [$algorithm, $hash] = explode('-', $meta['dist']['integrity'], 2);
        if ('sha512' !== $algorithm || !hash_equals($hash, base64_encode(hash('sha512', $tarball, true)))) {
            throw new \RuntimeException('esbuild download failed the checksum test.');
        }

        if (!is_dir($dir)) {
            mkdir($dir, 0o777, true);
        }
        $archive = $dir.'/package.tgz';
        file_put_contents($archive, $tarball);
        $inner = $windows ? 'package/esbuild.exe' : 'package/bin/esbuild';
        (new \PharData($archive))->extractTo($dir, $inner, true);
        rename($dir.'/'.$inner, $binary);
        chmod($binary, 0o755);
        unlink($archive);

        return $binary;
    }
}
